<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(DefaultTargetFrameworks)</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>NetCorePal.OpenTelemetry.Diagnostics</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenTelemetry" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\NetCorePal.Extensions.Primitives\NetCorePal.Extensions.Primitives.csproj" />
  </ItemGroup>
</Project>

