<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(DefaultTargetFrameworks)</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>NetCorePal.Extensions.NewtonsoftJson</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Newtonsoft.Json"/>
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\NetCorePal.Extensions.Domain.Abstractions\NetCorePal.Extensions.Domain.Abstractions.csproj" />
    </ItemGroup>
</Project>
