using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace NetCorePal.Extensions.Repository.EntityFrameworkCore.SourceGenerators
{
    [Generator]
    public class AppDbContextBaseSourceGenerator : IIncrementalGenerator
    {
        private readonly IReadOnlyCollection<string> dbContextBaseNames = new[]
            { "AppDbContextBase", "AppIdentityDbContextBase", "AppIdentityUserContextBase" };

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var syntaxProvider = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: (node, _) => node is TypeDeclarationSyntax,
                    transform: (syntaxContext, _) => (TypeDeclarationSyntax)syntaxContext.Node)
                .Where(tds => tds != null);

            var compilationAndTypes = context.CompilationProvider.Combine(syntaxProvider.Collect());

            context.RegisterSourceOutput(compilationAndTypes, (spc, source) =>
            {
                var (compilation, typeDeclarations) = source;
                foreach (var tds in typeDeclarations)
                {
                    var semanticModel = compilation.GetSemanticModel(tds.SyntaxTree);
                    var symbol = semanticModel.GetDeclaredSymbol(tds);
                    if (symbol is INamedTypeSymbol namedTypeSymbol)
                    {
                        if (!InheritsFromDbContextBase(namedTypeSymbol))
                        {
                            continue;
                        }

                        List<INamedTypeSymbol> ids = GetAllStrongTypedId(compilation);
                        GenerateValueConverters(spc, ids, namedTypeSymbol);
                        Generate(spc, namedTypeSymbol, ids);
                    }
                }
            });
        }

        private void Generate(SourceProductionContext context, INamedTypeSymbol dbContextType, List<INamedTypeSymbol> ids)
        {
            var ns = dbContextType.ContainingNamespace.ToString();
            string className = dbContextType.Name;
            string abstractModifier = dbContextType.IsAbstract ? "abstract " : "";

            StringBuilder sb = new();
            foreach (var id in ids)
            {
                sb.AppendLine($@"            configurationBuilder.Properties<global::{id.ContainingNamespace}.{id.Name}>().HaveConversion<global::{dbContextType.ContainingNamespace}.{dbContextType.Name}ValueConverters.{id.ContainingNamespace}.{id.Name}ValueConverter>();");
            }

            string source = $@"// <auto-generated/>
using Microsoft.EntityFrameworkCore;
using NetCorePal.Extensions.Repository.EntityFrameworkCore;
namespace {ns}
{{
    /// <summary>
    /// {className}ValueConverterConfigure
    /// </summary>
    public {abstractModifier}partial class {className}
    {{
        /// <summary>
        /// ConfigureStronglyTypedIdValueConverter
        /// </summary>
        /// <param name=""configurationBuilder""></param>
        protected override void ConfigureStronglyTypedIdValueConverter(ModelConfigurationBuilder configurationBuilder)
        {{
{sb}
        }}
    }}
}}
";
            context.AddSource($"{className}ValueConverterConfigure.g.cs", SourceText.From(source, Encoding.UTF8));
        }

        private void GenerateValueConverters(SourceProductionContext context, List<INamedTypeSymbol> ids, INamedTypeSymbol dbContextType)
        {
            foreach (var idType in ids)
            {
                var ns = idType.ContainingNamespace.ToString();
                StringBuilder source = new($@"// <auto-generated/>
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using System;
namespace {dbContextType.ContainingNamespace}.{dbContextType.Name}ValueConverters.{ns}
{{
");

                var className = $"global::{idType.ContainingNamespace}.{idType.Name}";
                source.Append($@"
    /// <summary>
    /// {idType.Name}ValueConverter
    /// </summary>
    public class {idType.Name}ValueConverter : ValueConverter<{className}, {idType.AllInterfaces.First(t => t.Name == "IStronglyTypedId").TypeArguments[0].Name}>
    {{
        /// <summary>
        /// Constructor
        /// </summary>
        public {idType.Name}ValueConverter() : base(p => p.Id, p => new {className}(p)) {{ }}
    }}
");

                source.Append($@"
}}
");
                context.AddSource($"{dbContextType.ContainingNamespace}.{dbContextType.Name}ValueConverters.{ns}.{idType.Name}ValueConverter.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
            }
        }
        
        private List<INamedTypeSymbol> GetAllTypes(IAssemblySymbol assemblySymbol)
        {
            var types = new List<INamedTypeSymbol>();
            GetTypesInNamespace(assemblySymbol.GlobalNamespace, types);
            return types;
        }
        
        private List<INamedTypeSymbol> GetAllStrongTypedId(Compilation compilation)
        {
            var list = GetStrongTypedIdFromCurrentProject(compilation);
            list.AddRange(GetStrongTypedIdFromReferences(compilation));
            return list;
        }

        private List<INamedTypeSymbol> GetStrongTypedIdFromCurrentProject(Compilation compilation)
        {
            List<INamedTypeSymbol> strongTypedIds = new();
            foreach (var syntaxTree in compilation.SyntaxTrees)
            {
                if (syntaxTree.TryGetText(out var sourceText) &&
                    !sourceText.ToString().Contains("StronglyTypedId"))
                {
                    continue;
                }

                var semanticModel = compilation.GetSemanticModel(syntaxTree);
                var typeDeclarationSyntaxs = syntaxTree.GetRoot().DescendantNodesAndSelf().OfType<TypeDeclarationSyntax>();
                foreach (var tds in typeDeclarationSyntaxs)
                {
                    var symbol = semanticModel.GetDeclaredSymbol(tds);
                    if (symbol is INamedTypeSymbol namedTypeSymbol && IsStrongTypedId(namedTypeSymbol))
                    {
                        strongTypedIds.Add(namedTypeSymbol);
                    }
                }
            }

            return strongTypedIds;
        }

        private List<INamedTypeSymbol> GetStrongTypedIdFromReferences(Compilation compilation)
        {
            var refs = compilation.References.Where(p => p.Properties.Kind == MetadataImageKind.Assembly).ToList();
            List<INamedTypeSymbol> strongTypedIds = new();
            foreach (var r in refs)
            {
                if (compilation.GetAssemblyOrModuleSymbol(r) is not IAssemblySymbol assembly)
                {
                    continue;
                }

                var nameprefix = compilation.AssemblyName?.Split('.')[0];
                if (assembly.Name.StartsWith(nameprefix))
                {
                    var types = GetAllTypes(assembly);
                    strongTypedIds.AddRange(types.Where(IsStrongTypedId));
                }
            }

            return strongTypedIds;
        }

        

        private void GetTypesInNamespace(INamespaceSymbol namespaceSymbol, List<INamedTypeSymbol> types)
        {
            types.AddRange(namespaceSymbol.GetTypeMembers());
            foreach (var subNamespaceSymbol in namespaceSymbol.GetNamespaceMembers())
            {
                GetTypesInNamespace(subNamespaceSymbol, types);
            }
        }

        private bool IsStrongTypedId(INamedTypeSymbol type)
        {
            return type.TypeKind == TypeKind.Class &&
                   type.AllInterfaces.Any(p => p.Name == "IStronglyTypedId");
        }

        private bool InheritsFromDbContextBase(INamedTypeSymbol type)
        {
            var baseType = type.BaseType;
            while (baseType != null)
            {
                if (dbContextBaseNames.Contains(baseType.Name))
                {
                    return true;
                }
                baseType = baseType.BaseType;
            }
            return false;
        }
    }
}