<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(DefaultTargetFrameworks)</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>NetCorePal.SkyApm.Diagnostics</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="SkyAPM.Utilities.DependencyInjection" />
        <PackageReference Include="Microsoft.Extensions.Options" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\NetCorePal.Extensions.DistributedLocks.Redis\NetCorePal.Extensions.DistributedLocks.Redis.csproj" />
      <ProjectReference Include="..\NetCorePal.Extensions.Primitives\NetCorePal.Extensions.Primitives.csproj" />
    </ItemGroup>
</Project>
