using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Collections.Generic;
using System.Data;
using System.Diagnostics;
using System.Linq;
using System.Reflection.Emit;
using System.Text;

namespace NetCorePal.Extensions.Repository.EntityframeworkCore.CodeGenerators
{
    [Generator]
    public class EFContextSourceGenerator : ISourceGenerator
    {
        public void Execute(GeneratorExecutionContext context)
        {

            context.AnalyzerConfigOptions.GlobalOptions.TryGetValue("build_property.RootNamespace", out var rootNamespace);
            if (rootNamespace == null)
            {
                return;
            }


            var compilation = context.Compilation;
            foreach (var syntaxTree in compilation.SyntaxTrees)
            {
                if (syntaxTree.TryGetText(out var sourceText) &&
                    !sourceText.ToString().Contains("EFContext"))
                {
                    continue;
                }
                var semanticModel = compilation.GetSemanticModel(syntaxTree);
                if (semanticModel == null)
                {
                    continue;
                }

                var typeDeclarationSyntaxs = syntaxTree.GetRoot().DescendantNodesAndSelf().OfType<TypeDeclarationSyntax>();
                foreach (var tds in typeDeclarationSyntaxs)
                {

                    var symbol = semanticModel.GetDeclaredSymbol(tds);
                    if (!(symbol is INamedTypeSymbol)) return;
                    INamedTypeSymbol namedTypeSymbol = (INamedTypeSymbol)symbol;


                    if (!namedTypeSymbol.IsAbstract && namedTypeSymbol?.BaseType?.Name == "EFContext")
                    {
                        List<INamedTypeSymbol> ids = new List<INamedTypeSymbol>();
                        ids.AddRange(GetIdNamedTypeSymbol(context.Compilation.Assembly));


                        var refs = compilation.References.Where(p => p.Properties.Kind == MetadataImageKind.Assembly).ToList();
                        foreach (var r in refs)
                        {
                            var assembly = compilation.GetAssemblyOrModuleSymbol(r) as IAssemblySymbol;

                            if (assembly == null)
                            {
                                continue;
                            }

                            var nameprefix = compilation.AssemblyName?.Split('.').First();


                            if (assembly.Name.StartsWith(nameprefix))
                            {

                                ids.AddRange(GetIdNamedTypeSymbol(assembly));
                            }
                        }
                        if (ids.Count > 0)
                        {
                            Generate(context, namedTypeSymbol, ids, rootNamespace);
                        }
                    }
                }

            }
        }


        static List<INamedTypeSymbol> GetIdNamedTypeSymbol(IAssemblySymbol assemblySymbol)
        {
            List<INamedTypeSymbol> ids = new();
            var types = GetAllTypes(assemblySymbol);

            foreach (var type in types)
            {
                var stronglyTypedId = type.AllInterfaces.SingleOrDefault(t => t.Name == "IStronglyTypedId");
                if (!type.IsAbstract && type.AllInterfaces.Any(t => t.Name == "IStronglyTypedId"))
                {
                    ids.Add(type);
                }
            }
            return ids;
        }




        static List<INamedTypeSymbol> GetAllTypes(IAssemblySymbol assemblySymbol)
        {
            var types = new List<INamedTypeSymbol>();
            GetTypesInNamespace(assemblySymbol.GlobalNamespace, types);
            return types;
        }

        static void GetTypesInNamespace(INamespaceSymbol namespaceSymbol, List<INamedTypeSymbol> types)
        {
            // 获取当前命名空间中的类型
            types.AddRange(namespaceSymbol.GetTypeMembers());

            // 遍历所有子命名空间
            foreach (var subNamespaceSymbol in namespaceSymbol.GetNamespaceMembers())
            {
                GetTypesInNamespace(subNamespaceSymbol, types);
            }
        }


        private void Generate(GeneratorExecutionContext context, INamedTypeSymbol dbContextType, List<INamedTypeSymbol> ids, string rootNamespace)
        {
            var ns = dbContextType.ContainingNamespace.ToString();
            string className = dbContextType.Name;


            StringBuilder sb = new StringBuilder();

            foreach (var id in ids)
            {
                var idName = id.Name;
                sb.AppendLine($@"            configurationBuilder.Properties<{id.ContainingNamespace}.{id.Name}>().HaveConversion<{idName}ValueConverter>();");
            }
            string source = $@"// <auto-generated/>
using Microsoft.EntityFrameworkCore;
using NetCorePal.Extensions.Repository.EntityframeworkCore;
using {rootNamespace}.ValueConverters;
namespace {ns}
{{
    public partial class {className} : EFContext
    {{
        private void ConfigureStronglyTypedIdValueConverter(ModelConfigurationBuilder configurationBuilder)
        {{
{sb}
        }}
    }}
}}
";

            context.AddSource($"{className}ValueConverter.g.cs", source);
        }

        public void Initialize(GeneratorInitializationContext context)
        {

        }
    }
}