<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(DefaultTargetFrameworks)</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>NetCorePal.Extensions.DistributedLocks</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AsyncKeyedLock" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    </ItemGroup>

</Project>
