<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(DefaultTargetFrameworks)</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>NetCorePal.Context.CAP</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="DotNetCore.CAP"/>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\NetCorePal.Context.Abstractions\NetCorePal.Context.Abstractions.csproj" />
    <ProjectReference Include="..\NetCorePal.Extensions.DistributedTransactions.CAP\NetCorePal.Extensions.DistributedTransactions.CAP.csproj" />
  </ItemGroup>
</Project>
