using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Linq;
using System.Text;

[Generator]
public class DomainEventToIntegrationEventMetadataGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: (node, _) => node is ClassDeclarationSyntax,
                transform: (ctx, _) => (ClassDeclarationSyntax)ctx.Node)
            .Where(c => c != null);

        var compilationAndClasses = context.CompilationProvider.Combine(classDeclarations.Collect());

        context.RegisterSourceOutput(compilationAndClasses, (spc, source) =>
        {
            var (compilation, classes) = source;
            var relations = new List<(string DomainEventType, string[] IntegrationEventTypes)>();

            foreach (var classDecl in classes)
            {
                var semanticModel = compilation.GetSemanticModel(classDecl.SyntaxTree);
                var symbol = semanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;
                if (symbol == null) continue;
                var converterInterface = symbol.AllInterfaces.FirstOrDefault(i =>
                    i.IsGenericType && i.Name == "IIntegrationEventConverter");
                if (converterInterface == null) continue;
                var domainEventType = converterInterface.TypeArguments[0].ToDisplayString();
                var integrationEventType = converterInterface.TypeArguments[1].ToDisplayString();
                // 这里假设每个领域事件只对应一个集成事件，后续如需支持多个事件可扩展
                var integrationEventTypes = new List<string> { integrationEventType };
                relations.Add((domainEventType, integrationEventTypes.ToArray()));
            }

            if (relations.Count > 0)
            {
                var sb = new StringBuilder();
                sb.AppendLine("// <auto-generated/>\nusing System;\nusing NetCorePal.Extensions.CodeAnalysis.Attributes;");
                foreach (var rel in relations)
                {
                    var events = string.Join(", ", rel.IntegrationEventTypes.Select(e => $"\"{e}\""));
                    sb.AppendLine($"[assembly: DomainEventToIntegrationEventMetadataAttribute(\"{rel.DomainEventType}\", {events})]\n");
                }
                spc.AddSource("DomainEventToIntegrationEventMetadata.g.cs", sb.ToString());
            }
        });
    }
} 