<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(DefaultTargetFrameworks)</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="StackExchange.Redis" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\NetCorePal.Extensions.Jwt\NetCorePal.Extensions.Jwt.csproj" />
    </ItemGroup>
</Project>
