<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(DefaultTargetFrameworks)</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>NetCorePal.Extensions.Snowflake.Consul</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Consul" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks"/>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\NetCorePal.Extensions.Snowflake\NetCorePal.Extensions.Snowflake.csproj" />
  </ItemGroup>
</Project>
