<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(DefaultTargetFrameworks)</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>NetCorePal.Context.AspNetCore</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Reactive"/>
    <PackageReference Include="Microsoft.Extensions.DiagnosticAdapter"/>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\NetCorePal.Context.Abstractions\NetCorePal.Context.Abstractions.csproj" />
  </ItemGroup>
</Project>
